### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by bingoIsCoder** [quickly/quickly#133]
when I run the example as QMLify doc. I met such error:
_path.js:33
function normalizeStringWin32(path, allowAboveRoot) {
RangeError: Maximum call stack size exceeded
    at normalizeStringWin32 (path.js:33:30)
    at Object.normalize (path.js:428:14)
    at Object.join (path.js:549:18)
    at findFile (C:\Users\foo\AppData\Roaming\npm\node_modules\qmlify\lib\util.js:39:48)
    at findFile (C:\Users\foo\AppData\Roaming\npm\node_modules\qmlify\lib\util.js:41:32)
    at findFile (C:\Users\foo\AppData\Roaming\npm\node_modules\qmlify\lib\util.js:41:32)
    at findFile (C:\Users\foo\AppData\Roaming\npm\node_modules\qmlify\lib\util.js:41:32)
    at findFile (C:\Users\foo\AppData\Roaming\npm\node_modules\qmlify\lib\util.js:41:32)
    at findFile (C:\Users\foo\AppData\Roaming\npm\node_modules\qmlify\lib\util.js:41:32)
    at findFile (C:\Users\foo\AppData\Roaming\npm\node_modules\qmlify\lib\util.js:41:32)_

does anyone know this?

**Comment by bingoIsCoder** [comment]
the cmd is:  qmlify -d src

**Comment by Jeruntu** [comment]
I also tried the example and couldn't get it to work. I think the documentation has a mistake or is outdated:
It says 

> Now just run qmlify on your src directory like this:
`$ qmlify -d src`

I run this command in src dir with the example app.js and response is:
_Not enough non-option arguments: got 0, need at least 1_

I read the help and it say -d stands for out-dir, where the output built files go. So I assumed it should be:
`$ qmlify src -d build`
Which I run from the parent dir of src.

However that gives me a very similar error that you (bingolsCoder) are also experiencing:
_RangeError: Maximum call stack size exceeded
    at normalizeString (path.js:57:25)
    at Object.normalize (path.js:372:14)
    at Object.join (path.js:490:18)
    at findFile (C:\source\util.js:28:28)
    at findFile (C:\source\util.js:32:16)
    at findFile (C:\source\util.js:32:16)
    at findFile (C:\source\util.js:32:16)
    at findFile (C:\source\util.js:32:16)
    at findFile (C:\source\util.js:32:16)
    at findFile (C:\source\util.js:32:16)_

I know Qt 5.12 will update the JS engine to support ECMA 2016, but until then and maybe even after this is a very handy tool! 

Any help will be highly appreciated.
