### ISSUE TITLE
qmlify: ImportError: Unable to find module: quickly-polyfills

### ISSUE THREAD

**Issue by uralbash** [quickly/quickly#25]
I'm trying to run the example https://github.com/quickly/quickly-skeleton

``` bash
$ make
Makefile:595: warning: overriding recipe for target 'qrc_resources.cpp'
Makefile:592: warning: ignoring old recipe for target 'qrc_resources.cpp'

qmlify -d qml-qmlified ../src/qml
Using babel for app.js

/source/dependencies.js:72
    throw new ImportError(`Unable to find module: ${importPath}`)
          ^
ImportError: Unable to find module: quickly-polyfills (imported from app.js)
    at _require (/source/dependencies.js:72:11)
    at JSFile.require (/source/basefile.js:60:20)
    at JSFile.injectRequire (/source/jsfile.js:159:33)
    at JSFile.transform (/source/jsfile.js:62:18)
    at JSFile.build (/source/basefile.js:80:18)
    at Bundle.build (/source/bundle.js:163:14)
    at Bundle.build_dir (/source/bundle.js:109:26)
    at Bundle.build_all (/source/bundle.js:65:14)
    at Object.build_dir (/source/index.js:33:12)
    at Object.<anonymous> (/home/user/.npm-global/lib/node_modules/qmlify/bin/qmlify.bin.js:35:16)
Makefile:561: recipe for target 'qml-qmlified/resources.qrc' failed
make: *** [qml-qmlified/resources.qrc] Error 1

```

**Comment by iBelieve** [comment]
Did you run `qpm install` and have a `vendor` folder in the project?

**Comment by uralbash** [comment]
Yes of course, I run it as described in README of https://github.com/quickly/quickly-skeleton
Tried with Qt5.5.1, Qt5.6.0 and node-5.11.0, node-6.1.0

Warnings when I run `qmake`:

``` bash
**Project MESSAGE: This project is using private headers and will therefore be tied to this specific Qt module build version.
Project MESSAGE: Running this project against other versions of the Qt modules may crash at any arbitrary point.
Project MESSAGE: This is not a bug, but a result of using Qt internals. You have been warned!
/home/user/Projects/bin/Qt55/5.5/gcc_64/bin/rcc: File does not exist 'qml-qmlified/resources.qrc'**
```

`vendor` directory:

``` bash
$ tree vendor/

vendor/
├── com
│   └── sonrisesoftware
│       └── quickly
│           ├── dependencies
│           │   ├── assert
│           │   │   └── assert.js
│           │   ├── aurelia-polyfills
│           │   │   └── src
│           │   │       ├── array.js
│           │   │       ├── collections.js
│           │   │       ├── number.js
│           │   │       ├── object.js
│           │   │       ├── reflect.js
│           │   │       ├── string.js
│           │   │       └── symbol.js
│           │   ├── es6-promise
│           │   │   └── dist
│           │   │       └── es6-promise.js
│           │   ├── inherits
│           │   │   └── inherits.js
│           │   ├── punycode
│           │   │   └── punycode.js
│           │   ├── querystring
│           │   │   ├── decode.js
│           │   │   ├── encode.js
│           │   │   └── index.js
│           │   ├── url
│           │   │   ├── url.js
│           │   │   └── util.js
│           │   ├── util
│           │   │   ├── support
│           │   │   │   └── isBuffer.js
│           │   │   └── util.js
│           │   └── whatwg-fetch
│           │       └── fetch.js
│           ├── LICENSE
│           ├── nodejs
│           │   ├── basemodule.cpp
│           │   ├── basemodule.h
│           │   ├── filesystem.cpp
│           │   ├── filesystem.h
│           │   ├── path.cpp
│           │   ├── path.h
│           │   ├── process.cpp
│           │   └── process.h
│           ├── plugin.cpp
│           ├── plugin.h
│           ├── polyfills
│           │   ├── http.js
│           │   ├── index.js
│           │   ├── promise.js
│           │   ├── string.js
│           │   ├── timeout.js
│           │   └── Timeout.qml
│           ├── qmldir
│           ├── qmlify.pri
│           ├── qpm.json
│           ├── quickly.json
│           ├── quickly.pri
│           ├── README.md
│           └── resources.qrc
└── vendor.pri

18 directories, 44 files

```

``` bash
$ cat quickly-skeleton.pro 

include(vendor/vendor.pri)

QT += qml quick

SOURCES += src/main.cpp
QMLIFY += src/qml
```

**Comment by bingosoft** [comment]
i have the same issue. who knows the solution?

**Comment by glebovitz** [comment]
so this project is dead?

**Comment by larpon** [comment]
I don't hope it's dead. It's the closests thing I've found that can/could bring node modules to Qt :/

**Comment by glebovitz** [comment]
Would like it to be alive. Could never get qmlify to work on my mac. Want to use it for iOS develooment.

**Comment by kjetilge** [comment]
Me too!

**Comment by glebovitz** [comment]
Anyone have a solution to this issue?

**Comment by DjianR** [comment]
same problem here :(

**Comment by sevenbitbyte** [comment]
:( just hit this problem... really love this project though

**Comment by n8behavior** [comment]
Me too.  Trying to decide if it's worth resurrecting this project or going another direction :thinking:

**Comment by NathanPB** [comment]
So, 2 years later, do we already have an alternative?
